### ISSUE TITLE
US: Create and Edit Categories

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#11]
As a **Site Admin** I can **create and edit categories for activities** so that **they can be organized and placed appropriately.**

### Acceptance Criteria:
- [x] The site admin can create categories from the admin dashboard.
- [x] The site admin can edit categories from the admin dashboard.
- [x] The system ensures category names are unique. 
- [x] Show error messages for duplicate names.
- [x] Show error messages for empty names.

### Tasks
- [x] Develop the category management interface on the admin dashboard.
- [x] Implement functionality to create and edit categories by specifying and updating a category name.
- [x] Add validation to ensure category names are unique and display appropriate error messages for duplicates or empty names.
