### ISSUE TITLE
US: View Categories

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#12]
As a **Staff user / User** I can **click, view, and filter on each category** so that **I can select which category I want to explore.**

### Acceptance Criteria:

- [x] Users can view a list of all available categories.
- [x] Users can click on a category to view all associated activities.

### Tasks
- [x] Develop a category list interface to display all available categories.
- [x] Implement functionality to navigate to activities associated with a clicked category.
