### ISSUE TITLE
US: View Comments on Activities

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#20]
As a **User** I can **view comments** so that **I can make an informed decision about which activity to choose based on other users' input.**

### Acceptance Criteria:

- [x] Users can see a list of comments for each activity.
- [x] The comments must be displayed in a clear and organized manner.

### Tasks
- [x] Implement functionality to display comments for each activity.
