### ISSUE TITLE
US: Site admin to manage reviews

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#22]
As a **Site admin** I can **edit and delete all reviews** so that **I can ensure there are no offensive comments.**

### Acceptance Criteria:

- [x] Site admins can view all reviews on activities.
- [x] Site admins can edit reviews to remove or alter offensive content.
- [x] Site admins can delete reviews that violate guidelines.

### Tasks
- [x] Implement functionality for site admins to view all reviews.
