### ISSUE TITLE
US: Delete categories

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#24]
As a **Site admin** I can **delete categories that are no longer needed** so that **he category list remains relevant and up-to-date.**

### Acceptance Criteria:

- [x] Site admin can select and delete categories in the admin panel.
- [x] Deleted categories must be immediately removed from the category list upon confirmation.

### Tasks

- [x] Implement functionality to select and delete categories.
- [x] Ensure the immediate removal of deleted categories from the category list upon confirmation.
