### ISSUE TITLE
US: Add Staff User permission

### ISSUE THREAD

**Issue by Malinchristina** [Malinchristina/handbook-for-burnout#31]
As a **Site Admin** I can **give a Staff User permission** so that **they can access admin features, except adding categories**

### Acceptance Criteria:

- [x] Given the user has a registered account, Site Admin can assign all admin features to a Staff User, except the ability to add categories.
- [x] Staff Users can access all assigned admin features but are restricted from adding categories.

Tasks:
- [x] Implement functionality to select and assign permissions to a Staff User.
- [x] Ensure Staff Users' access is restricted to assigned permissions, excluding adding categories.
